sudo: required
services:
  - docker # need to setup to run test containers
env:
  global:
    - GIT_SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1 # this will disable gcloud cli prompts during CI build
before_install: 
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null; # isntall gcloud sdk
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl # install kubectl
  - gcloud auth activate-service-account --key-file service-account.json # used to access gcloud account
  - gcloud config set project multi-k8s-347610
  - gcloud config set compute/zone asia-south1-a
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t adibhatk96/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true adibhatk96/react-test npm test

deploy:
  provider: script # use custom script for k8s deployment 
  script: bash ./deploy.sh
  on:
    branch: master